name: flutter_practice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  styled_widget: ^0.4.1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  url_launcher: ^6.2.6
  logger: ^2.2.0
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

